// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Proyecto_Web_ll.Models;
using System;

namespace Proyecto_Web_ll.Migrations
{
    [DbContext(typeof(MvcToyotaContext))]
    [Migration("20180219023928_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Proyecto_Web_ll.Models.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CedulaJuridica")
                        .IsRequired();

                    b.Property<string>("DireccionFisica")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PaginaWeb");

                    b.Property<string>("Sector")
                        .IsRequired();

                    b.Property<int?>("telefono");

                    b.HasKey("ID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Proyecto_Web_ll.Models.Contacto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido_Uno")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Correo");

                    b.Property<int>("Id_Cliente");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Puesto")
                        .IsRequired();

                    b.Property<int>("Telefono")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Contacto");
                });

            modelBuilder.Entity("Proyecto_Web_ll.Models.Reunion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EnrollmentDate");

                    b.Property<int?>("Id_Cliente");

                    b.Property<int>("Id_Usuario");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("Virtual");

                    b.HasKey("ID");

                    b.ToTable("Reunion");
                });

            modelBuilder.Entity("Proyecto_Web_ll.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido_Uno");

                    b.Property<string>("Contrasenna")
                        .IsRequired();

                    b.Property<string>("Correo");

                    b.Property<string>("Nombre");

                    b.Property<string>("Puesto");

                    b.Property<int?>("Telefono");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
